spring:
  application:
    name: daddyPcBackend

  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  ai:
    model:
      chat: openai
    openai:
      base-url: https://api.siliconflow.com/v1
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: MiniMaxAI/MiniMax-M3
          temperature: 0.3
      embedding:
        options:
          model: Qwen/Qwen3-Embedding-0.6B
          dimensions: 768


tavily:
  api-key: ${TAVILY_API}